version: "3"

services:
  nfs-server:
    deploy:
      resources:
        limits:
          memory: 256M
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "2049:2049"
    volumes:
      - /mnt/10TBUSB:/mnt/10TBUSB:rw
